#!/bin/bash

set -x

for CONFIG in Debug Release; do
    MONO_PATH=$(cd $PWD/Output/Linux/$CONFIG/lib; pwd)
    PATH=$MONO_PATH/../bin:$PATH
    MONO_EXE=$MONO_PATH/../bin/mono
    MONO_LIBDIR=$MONO_PATH/mono/4.5
    common_args=/p:Configuration=$CONFIG\;NoCompilerStandardLib=false\;OutDir=$MONO_PATH/mono/4.5/\;SignAssembly=true\;DelaySign=false\;AssemblyOriginatorKeyFile=Dynamic.snk\;DefineConstants=SIGNED%3BNO_HAVE_ADO_NET%3BHAVE_APP_DOMAIN%3BNO_HAVE_ASYNC%3BNO_HAVE_BIG_INTEGER%3BNO_HAVE_BINARY_FORMATTER%3BNO_HAVE_BINARY_SERIALIZATION%3BNO_HAVE_BINARY_EXCEPTION_SERIALIZATION%3BHAVE_CAS%3BHAVE_CHAR_TO_LOWER_WITH_CULTURE%3BHAVE_CHAR_TO_STRING_WITH_CULTURE%3BHAVE_COM_ATTRIBUTES%3BHAVE_COMPONENT_MODEL%3BHAVE_CONCURRENT_COLLECTIONS%3BHAVE_COVARIANT_GENERICS%3BNO_HAVE_DATA_CONTRACTS%3BHAVE_DATE_TIME_OFFSET%3BHAVE_DB_NULL_TYPE_CODE%3BHAVE_DYNAMIC%3BHAVE_EMPTY_TYPES%3BHAVE_ENTITY_FRAMEWORK%3BHAVE_EXPRESSIONS%3BHAVE_FAST_REVERSE%3BHAVE_FSHARP_TYPES%3BHAVE_FULL_REFLECTION%3BHAVE_GUID_TRY_PARSE%3BHAVE_HASH_SET%3BHAVE_ICLONEABLE%3BHAVE_ICONVERTIBLE%3BNO_HAVE_IGNORE_DATA_MEMBER_ATTRIBUTE%3BHAVE_INOTIFY_COLLECTION_CHANGED%3BHAVE_INOTIFY_PROPERTY_CHANGING%3BHAVE_ISET%3BHAVE_LINQ%3BHAVE_MEMORY_BARRIER%3BHAVE_METHOD_IMPL_ATTRIBUTE%3BHAVE_NON_SERIALIZED_ATTRIBUTE%3BHAVE_READ_ONLY_COLLECTIONS%3BHAVE_REFLECTION_EMIT%3BHAVE_SECURITY_SAFE_CRITICAL_ATTRIBUTE%3BHAVE_SERIALIZATION_BINDER_BIND_TO_NAME%3BHAVE_STREAM_READER_WRITER_CLOSE%3BHAVE_STRING_JOIN_WITH_ENUMERABLE%3BHAVE_TIME_SPAN_PARSE_WITH_CULTURE%3BHAVE_TIME_SPAN_TO_STRING_WITH_CULTURE%3BHAVE_TIME_ZONE_INFO%3BHAVE_TRACE_WRITER%3BHAVE_UNICODE_SURROGATE_DETECTION%3BHAVE_VARIANT_TYPE_PARAMETERS%3BHAVE_VERSION_TRY_PARSE%3BNO_HAVE_XLINQ%3BHAVE_XML_DOCUMENT%3BHAVE_XML_DOCUMENT_TYPE%3BHAVE_CONCURRENT_DICTIONARY%3BRELEASE%3BNET45

    $MONO_PATH/../bin/mono $MONO_PATH/mono/4.5/xbuild.exe ../external/Newtonsoft.Json/Src/Newtonsoft.Json/Newtonsoft.Json.csproj $common_args /t:Rebuild


    $MONO_EXE $MONO_LIBDIR/sn.exe -R $MONO_LIBDIR/Newtonsoft.Json.dll ../external/Newtonsoft.Json/Src/Newtonsoft.Json/Dynamic.snk
    $MONO_PATH/../bin/mono $MONO_PATH/mono/4.5/gacutil.exe -i $MONO_PATH/mono/4.5/Newtonsoft.Json.dll
done

